# This file is autogenerated by edgy.project code generator.
# All changes will be overwritten.

import os
from setuptools import setup, find_packages

root_dir = os.path.dirname(os.path.abspath(__file__))

tolines = lambda c: list(filter(None, map(lambda s: s.strip(), c.split('\n'))))


def read(filename, flt=None):
    try:
        with open(filename) as f:
            content = f.read().strip()
            return flt(content) if callable(flt) else content
    except EnvironmentError:
        return ''


# Py3 compatibility hacks, borrowed from IPython.
try:
    execfile
except NameError:

    def execfile(fname, globs, locs=None):
        locs = locs or globs
        exec(compile(open(fname).read(), fname, "exec"), globs, locs)


version_ns = {}
try:
    execfile(
        os.path.join(root_dir, 'bonobo_sqlalchemy/_version.py'), version_ns)
except EnvironmentError:
    version = 'dev'
else:
    version = version_ns.get('__version__', 'dev')

setup(
    name='bonobo_sqlalchemy',
    description='Bonobo SQLAlchemy Extension',
    license='Apache License, Version 2.0',
    install_requires=['bonobo >=0.2.2,<0.3', 'toolz', 'SQLAlchemy >=1.1,<1.2'],
    version=version,
    long_description=read('README.rst'),
    classifiers=read('classifiers.txt', tolines),
    packages=find_packages(exclude=['ez_setup', 'example', 'test']),
    include_package_data=True,
    extras_require={'dev': ['bonobo[dev]']},
    url='https://www.bonobo-project.org/extension/sqlalchemy',
    download_url=
    'https://github.com/python-bonobo/bonobo-sqlalchemy/tarball/{version}'.
    format(version=version), )
